### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by arvkonstantin** [viewst/pyTON#2]
On the latest version of the repository, the call to the request `getTransactions?address=EQAL7j_lEZn7DRvm29SdY5vWXD6l_en0OjalyeJYW8dzSpi4` ends in a crash with the Illegal instruction error. There is no stack trace.

**Comment by EmelyanenkoK** [comment]
Quite strange, it works on my server: https://toncenter.com/api/test/v2/getTransactions?address=EQAL7j_lEZn7DRvm29SdY5vWXD6l_en0OjalyeJYW8dzSpi4
What is the OS? Do other requests work?
It is possible, that shared library compiled on my machine will not work on some severely different os. You may try to compile your own tonlibjson shared library (see instructions here https://github.com/formony/ton_client/blob/master/docs/ton.md )

**Comment by arvkonstantin** [comment]
I have the most common Ubuntu distribution 18.04.3 LTS
Now I tried to build a library on my machine, I always get an error when I do make
```
/usr/bin/ld: /root/openssl-tree/lib/libcrypto.a(cryptlib.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
Tomorrow I'll try to figure it out, but it seems to me that is not the problem. Because two weeks ago everything worked for me and it’s really strange

**Comment by EmelyanenkoK** [comment]
Is this issue resolved?
